configs:
  # general optimization parameters:
  batch_size: 6000
  max_epochs: 2000
  learning_rate: .005
  min_delta: 0.00000008
  patience: 50
  single_epoch_test_run: True
  # data simulation parameters:
  missing_percentage: .9
  nitems: 400
  N: 10000
  # General model parameters:
  model: 'iwae'
  mirt_dim: 3
  hidden_layer_size: 200
  hidden_layer_size2: 100
  # parameters when model=='pvae':
  p_emb_dim: 16
  p_hidden_dim: 32
  p_latent_dim: 64
  p_hidden_layer_dim: 32
  # parameters when model=='iwae':
  n_iw_samples: 5
  # parameters when model=='cvae':
  hidden_layer_size3: 50

