configs:
  # general optimization parameters:
  batch_size: 1000
  max_epochs: 1000
  learning_rate: .005
  min_delta: 0.0000008
  patience: 30
  single_epoch_test_run: True
  # data simulation parameters:
  simulate: True
  save: True
  missing_percentage: 0
  nitems: 28
  N: 10000
  iteration: 1
  # General model parameters:
  model: 'idvae'
  mirt_dim: 3
  hidden_layer_size: 40
  hidden_layer_size2: 20
  # parameters when model=='pvae':
  p_emb_dim: 32
  p_hidden_dim: 32
  p_latent_dim: 32
  p_hidden_layer_dim: 32
  # parameters when model=='iwae':
  n_iw_samples: 5
  # parameters when model=='cvae':
  hidden_layer_size3: 50
  # onlyy for main
  which_data: 'dylan'
