configs:
  # general optimization parameters:
  batch_size: 32
  max_epochs: 2000
  learning_rate: .005
  min_delta: .0000008
  patience: 10
  single_epoch_test_run: False
  # data simulation parameters:
  simulate: True
  save: False
  missing_percentage: 0.5
  N: 10000
  covariance: 0
  iteration: 2
  # General model parameters:
  model: 'cvae'
  mirt_dim: 3
  hidden_layer_size: 20
  hidden_layer_size2: 20
  beta: 1
  n_iw_samples: 5
  cholesky: False
  sample_cor: True
  # parameters when model=='pvae':
  p_emb_dim: 12
  p_hidden_dim: 24
  p_latent_dim: 24
  p_hidden_layer_dim: 24
  # parameters when model=='cvae':
  hidden_layer_size3: 10

