configs:
  # general optimization parameters:
  batch_size: 1000
  min_epochs: 1
  max_epochs: 50000
  learning_rate: .001 #.005
  min_delta: .000000008
  patience: 500
  single_epoch_test_run: False
  # data simulation parameters:
  simulate: True
  save: False
  missing_percentage: 0
  N: 1000
  iteration: 1
  # General model parameters:
  model: 'vae'
  mirt_dim: 3
  hidden_layer_size: 20
  hidden_layer_size2: 20
  beta: 1
  n_iw_samples: 1
  cor_theta: False
  cor_post: False
  # parameters when model=='pvae':
  p_emb_dim: 12
  p_hidden_dim: 24
  p_latent_dim: 24
  p_hidden_layer_dim: 24
  # parameters when model=='cvae':
  hidden_layer_size3: 10

